[package]
name = "raur"
version = "0.1.0"
authors = ["deciduously <bendlovy@gmail.com>"]

[dependencies]
clap = "~2.19.0"
clippy = {version = "*", optional = true}
hyper = "0.9"
toml = "0.2"

[features]
default = []
dev = ["clippy"]